### ISSUE TITLE
complexity tests are flaky

### ISSUE THREAD

**Issue by jaraco** [jaraco/zipp#104]
As pleased as I was to discover the `big_o` library for evaluating complexity, the addition of those tests to the suite have introduced flakiness to the test suite. See [this run](https://github.com/jaraco/zipp/actions/runs/5538805898/jobs/10109118154) for example. I've seen several runs report "Linearithmic" complexity and some PyPy runs show "Cubic" complexity. Is there a way to make them less flaky?

**Comment by pberkes** [comment]
hi @jaraco  normally you should be able to make the tests more robust by increasing the `n_measurements`, `n_repeats`, and `n_timings` . 

Looking at the `zipp` code, it seems that those arguments are left at their default values, which means 10 measurements, 1 repeat and 1 timing per repeat.

Increasing the number of measurements between n_min and n_max would improve the accuracy of the complexity estimate, but usually robustness is achieved with higher n_repeats: big_o takes the minimum of the repeats, making sure that each repetition is not influenced by temporary system load, or initial caching , or similar.

Let me know if increasing these values helps!
