### ISSUE TITLE
zipp.Path does not resolve 'current dir' like pathlib.Path does

### ISSUE THREAD

**Issue by xtofl** [jaraco/zipp#111]
When extending a `pathlib.Path` with a sub-path containing 'special dirs' like `.` and `..`, it is able to resolve  them.

For `zipp.Path`, that is not the case:

```python
In [4]: (pathlib.Path(".") / "./README.md").is_file()
Out[4]: True   # as expected

In [5]: (zipp.Path("this-dir.zip") / "./README.md").is_file()
Out[5]: False  # <<< surprisingly different

In [6]: (zipp.Path("this-dir.zip") / "README.md").is_file()
Out[6]: True  # as expected
```

Of course, there is the 'very special' case where `..` would bring you out of the zip file in to the containing file system.  I think this case could be solved, but it's totally explicable to not support it.

```
In [7]: (pathlib.Path(".") / "../na-algo/README.md").is_file()
Out[7]: True

In [8]: (zipp.Path("this-dir.zip") / "../this-dir.zip/README.md").is_file()
Out[8]: False
```

Observed in version: 3.13.0 on ubuntu with python 3.8.12

**Comment by jaraco** [comment]
Thanks for the report. Although `zipp.Path` (and `zipfile.Path`) attempt to mirror the expectations of `pathlib.Path`, it aims mainly to provide compatibility in all cases and in some cases, there are inherent incompatibilities. Given that there exists a usable pattern to traverse the paths without special dirs, I'm not sure it's worth the extra complication to add support for them, especially given that special dirs aren't a feature of the zip model (that is `.` and `..` are features of a file system but not features of a zip file).

If adding the support could be possible without substantial complication, it's worth considering, especially if it provides value to users through less surprise or a more consistent model across domains. Can you say more about the case or cases where this concern arose and why it would be valuable to others?

**Comment by xtofl** [comment]
The concern arose when dealing with some kind of recording that could be represented either as a regular folder, or as a zip file.

Inside this recording, some references were made to other files in the recording.  The `.` was used to represent the base folder of the recording.

I must admit that in hindsight, that was a terrible idea, since it usually represents the current working directory and thus is associated with a process, and not with a file.
