### ISSUE TITLE
latest more-itertools is python3 only, so v0.6.0 is not compable with python 2.7

### ISSUE THREAD

**Issue by cztchoice** [jaraco/zipp#13]
this commit does not make is run on python 2.7:

https://github.com/jaraco/zipp/commit/b9e783fb44ee1957452b13cc464516f930b93a9b

we need use more-itertools==5.0.0

see here:
https://github.com/erikrose/more-itertools/commits/master/setup.py

**Comment by jaraco** [comment]
Late versions of pip will only download versions of a dependency suitable for that Python version. See the Travis CI runs for this project—they demonstrate that the project runs fine on Python 2.
