### ISSUE TITLE
Cannot install on python since more-itertools droped Python 2.7

### ISSUE THREAD

**Issue by Lesvek** [jaraco/zipp#22]
more-itertools dropped python 2.7 support in version 6.0.0. 

The fix would be to fix the version to 5.0.0 when installing with python 2.

I am, unfortunately stuck with Python 2. I'll try to submit a pull request addressing the problem later today.

**Comment by layday** [comment]
#20 will drop the dependency on `more-itertools` if it is merged.

**Comment by jaraco** [comment]
The pull request was #23, but the recommended approach is to use pip 9 or later. Is there a reason you can't install with pip 9 or later?

**Comment by Lesvek** [comment]
I found the root cause of the problem:

I was using an old version of devpi, which did not support _python\_requires_ as a cache.
The fix was to update devpi and completely delete the cache, as there was a bad copy of _more-itertools_ in it.

So, the complete fix was to:
* Make sure to use the latest version of _pip_
* Update devpi to the latest version without keeping the cache

**Comment by jaraco** [comment]
This report was a duplicate of #13.
