### ISSUE TITLE
Python 3.5 finds no matching distribution

### ISSUE THREAD

**Issue by Bengt** [jaraco/zipp#28]
I cannot install zipp 2.0.0 under CPython 3.5:

```
$ python -m pip install --quiet --upgrade -r requirements.d/venv.txt
00:04
 ERROR: Could not find a version that satisfies the requirement zipp==2.0.0 (from -r requirements.d/venv.txt (line 15)) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 1.0.0)
 ERROR: No matching distribution found for zipp==2.0.0 (from -r requirements.d/venv.txt (line 15))
```

Here is a public pipeline job erroring out because of that:

<https://gitlab.com/offis.energy/mosaik/mosaik.Demo_SemVer/-/jobs/408320225>

**Comment by Bengt** [comment]
This also affects PyPy 3.5.

**Comment by Bengt** [comment]
As a workaround, one can downgrade zipp to 1.0.0:

    pip install --quiet zipp==1.0.0

**Comment by Karrade7** [comment]
Looks like this breaks docker-compose. 
I opened an issue there too:
https://github.com/docker/compose/issues/7160

**Comment by johnthagen** [comment]
I think it would be helpful to put the actual supported versions of Python in the trove classifiers. As I understand it, `pip` can use that to know which packages to fall back to on PyPI.

**Comment by jaraco** [comment]
It's working as intended. [zipp 2.0.0 intentionally dropped support for Python 3.5](https://zipp.readthedocs.io/en/latest/history.html#v2-0-0), so it's invalid to attempt to install it in that environment. If your application wishes to support an earlier Python, your requirement specifiers must not exclude zipp 1.x.

> I think it would be helpful to put the actual supported versions of Python in the trove classifiers. As I understand it, `pip` can use that to know which packages to fall back to on PyPI.

I'm pretty sure `pip` only honors the `Requires-Python` directive (from `python_requires` in setup.cfg). Adding the trove classifiers is redundant, adds toil, and increases the possibility of being in conflict with `Requires-Python`. I'd rather avoid that maintenance burden (on this package and my implication, on the 140 other packages I maintain).
