### ISSUE TITLE
zipp 2.2.0 fails to build

### ISSUE THREAD

**Issue by amiantos** [jaraco/zipp#41]
We're getting failures to build that I've traced back to `zipp`. Here's some examples of output from pip:

```
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.1.2->-r /tmp/Requirements.txt (line 40))
  Downloading https://files.pythonhosted.org/packages/60/85/668bca4a9ef474ca634c993e768f12bd99af1f06bb90bb2655bc538a967e/zipp-2.2.0.tar.gz
[91m  Running setup.py (path:/tmp/pip-build-4n6a7neg/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.

[...]

Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a0/1f/9d/d132b3fbc38b33322681e3a7830c0a29fce7f55c3a06b85c65
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4n6a7neg/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpwcto5efwpip-wheel- --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-4n6a7neg/unknown/setup.py'
  
  ----------------------------------------
[91m  Failed building wheel for unknown
[0m  Running setup.py clean for unknown
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4n6a7neg/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-4n6a7neg/unknown/setup.py'
  
  ----------------------------------------
[91m  Failed cleaning build dir for unknown
```

Let me know what other info I can provide to diagnose this. Once I pin `zipp!=2.2.0` in my requirements file, the build error goes away.

**Comment by jaraco** [comment]
It works for me.

```
~ $ python3.5 -m pip-run --no-binary zipp --no-cache-dir zipp                                                                                                             
Collecting zipp
  Downloading zipp-1.1.0.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: zipp
  Building wheel for zipp (PEP 517) ... done
  Created wheel for zipp: filename=zipp-1.1.0-py2.py3-none-any.whl size=4625 sha256=f40ccdd266e8e37b59d91d83b6790764de1052d36adf7935d66516e482e10164
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-ll7n2q5h/wheels/67/db/8e/999d9ee17fdeaf67946dd9ef2a1308767d3d4c148ad2e5031f
Successfully built zipp
Installing collected packages: zipp
Successfully installed zipp-1.1.0
Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I notice that your pip is pulling down zipp 2.x, which is not compatible with Python 3.5. You should use a pip 9 or later with an index that honors Requires-Python.

It also looks like it's building from source, which shouldn't happen (it should use the wheel).

I also notice that when building from source, you aren't getting the proper package configuration. You probably need a later setuptools that supports declarative config (setup.cfg), but better would be to install from the wheel.

There weren't a lot of changes between 2.1 and 2.2 [except these](https://github.com/jaraco/zipp/compare/v2.1.0...v2.2.0) (implicating #36).

My guess is your index or your pip isn't honoring the new 'py36' tag on the package.

**Comment by horadla23** [comment]
> We're getting failures to build that I've traced back to `zipp`. Here's some examples of output from pip:
> 
> ```
> Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.1.2->-r /tmp/Requirements.txt (line 40))
>   Downloading https://files.pythonhosted.org/packages/60/85/668bca4a9ef474ca634c993e768f12bd99af1f06bb90bb2655bc538a967e/zipp-2.2.0.tar.gz
> �[91m  Running setup.py (path:/tmp/pip-build-4n6a7neg/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.
> 
> [...]
> 
> Running setup.py bdist_wheel for unknown: started
>   Running setup.py bdist_wheel for unknown: finished with status 'done'
>   Stored in directory: /root/.cache/pip/wheels/a0/1f/9d/d132b3fbc38b33322681e3a7830c0a29fce7f55c3a06b85c65
>   Running setup.py bdist_wheel for unknown: started
>   Running setup.py bdist_wheel for unknown: finished with status 'error'
>   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4n6a7neg/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpwcto5efwpip-wheel- --python-tag cp35:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/usr/lib/python3.5/tokenize.py", line 454, in open
>       buffer = _builtin_open(filename, 'rb')
>   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-4n6a7neg/unknown/setup.py'
>   
>   ----------------------------------------
> �[91m  Failed building wheel for unknown
> �[0m  Running setup.py clean for unknown
>   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4n6a7neg/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/usr/lib/python3.5/tokenize.py", line 454, in open
>       buffer = _builtin_open(filename, 'rb')
>   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-4n6a7neg/unknown/setup.py'
>   
>   ----------------------------------------
> �[91m  Failed cleaning build dir for unknown
> ```
> 
> Let me know what other info I can provide to diagnose this. Once I pin `zipp!=2.2.0` in my requirements file, the build error goes away.

+1

**Comment by horadla23** [comment]
`pip install --upgrade pip` solved it
