### ISSUE TITLE
easy_install installs zipp 3.0.0 on Python 2

### ISSUE THREAD

**Issue by idgserpro** [jaraco/zipp#45]
When using `easy_install` from Python 2, to install zipp, it installs version 3.0.0, which is not compatible with Python 2. When using `pip` it installs the correct version for Python 2. It is possible to have the same behavior as `pip` with `easy_install`?

**Comment by jaraco** [comment]
Unfortunately, no. `easy_install` is deprecated. Your only option with `easy_install` is to pin dependencies to a compatible version (perhaps as a pre-install workaround). This issue isn't going to affect just zipp, but any project that drops support for an older version of Python (including Python 2.6 and Python 3.x).
