### ISSUE TITLE
zipp 1.2.0 testing not python-2.7 compatible

### ISSUE THREAD

**Issue by 0-wiz-0** [jaraco/zipp#49]
I assume that zipp-1.x is intended to still be working with python-2.7. Free free to close if that's incorrect.

When running the self tests for it, there is the following failure:
````
ImportError: Failed to import test module: test_zipp
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/pkg/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/scratch/archivers/py-zipp1/work/zipp-1.2.0/test_zipp.py", line 28, in <module>
    import jaraco.itertools
  File "/usr/pkg/lib/python2.7/site-packages/jaraco/itertools.py", line 15, in <module>
    import collections.abc
ImportError: No module named abc
````
when I look at jaraco.itertools' `setup.cfg`, I see that it's only for python >= 3.6:
https://github.com/jaraco/jaraco.itertools/blob/master/setup.cfg#L21

**Comment by bhundven** [comment]
Also ran into this. Pinned to 1.1.1, works fine.

**Comment by jaraco** [comment]
> I assume that zipp-1.x is intended to still be working with python-2.7. 

Correct

The problem you have is that you've installed the test dependencies with an old version of pip, so you ended up with a `jaraco.itertools` that doesn't include the `from __future__ import absolute_import` so `import collections` ends up getting `jaraco.collections`, which has no `abc` submodule.

You'll want to install pip 9 or later before installing the dependencies or pin all of zipp's test dependencies in the environment before running the tests. There are some improvements to the test suite in jaraco/skeleton that I can probably incorporate (that update pip automatically).

**Comment by jaraco** [comment]
In 11d24c3, I've merged some commits from the skeleton that enable automatic upgrade of pip in tox environments. Does that fix the issue?

**Comment by 0-wiz-0** [comment]
I'm not using pip in my environment at all. pkgsrc uses the pypi source files for packaging.
The test dependencies in `setup.cfg` just say `jaraco.itertools` is needed, without pinning any version:
https://github.com/jaraco/zipp/blob/master/setup.cfg#L29
so the latest `jaraco.itertools` is installed, 0.5.0, which is marked as only for python 3.6 or newer:
https://github.com/jaraco/jaraco.itertools/blob/master/setup.cfg#L21

**Comment by jaraco** [comment]
If you're not using `tox` to run the tests, then you're on your own.

I'd still recommend using an installer that honors [PEP 345](https://www.python.org/dev/peps/pep-0345/) and [PEP 503](https://www.python.org/dev/peps/pep-0503/). Without that, you will run into problems any time a package drops support for some Python version; the problems are just more stark in the transition from Python 2 to 3.

Without a compliant installer, your next best bet is to build a wrapper for zipp tests that pre-installs compatible versions of (all transitive) dependencies so they're satisfied. You may be tempted to ask:

> Why not just pin to older versions?

That leaves this project indefinitely pinned to older versions.

> Why not use environment markers to declare compatible versions (i.e. `jaraco.itertools < 5; python_version < "3"`)?

That approach is generally unsustainable as it requires embedding metadata about `jaraco.itertools` into the metadata for `zipp` and would apply transitively. It's unnecessarily redundant to the metadata already present in the dependencies themselves.

Good luck.
