### ISSUE TITLE
Version: 0.0.0 in PKG-INFO

### ISSUE THREAD

**Issue by chuckwolber** [jaraco/zipp#58]
PKG-INFO file has "Version: 0.0.0". This breaks dependency checking for stuff like [nsenter](https://pypi.org/project/nsenter/) that specifies a minimum version of zipp (zipp>=0.5).

**Comment by jaraco** [comment]
Thanks for the report. Unfortunately, that's not what I find:

```
draft $ pip download --no-deps --no-binary zipp zipp
Collecting zipp
  Using cached zipp-3.1.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Saved ./zipp-3.1.0.tar.gz
draft $ tar xzf zipp-3.1.0.tar.gz
draft $ cat zipp-3.1.0/PKG-INFO | grep ^Version
Version: 3.1.0
```

I suspect what's happening is you're building from a GitHub tarball or in some environment where the `git` command isn't available and thus the repository metadata (tags) are missing.

This project uses `setuptools_scm` to keep a single source of truth for the source version in the repository metadata.

Please instead install from PyPI sdist or wheel with pip.

**Comment by chuckwolber** [comment]
Thanks you for looking in to this. I originally discovered this when I installed from PyPi, but I do not seem to be able to reproduce it any longer. I just tested the last several releases of Zipp posted on PyPi and was able to find a proper Version value in each. So I am not entirely sure what happened.

Thank you again for taking a look into this, and please accept my apologies for not doing enough research before submitting a bug.
