### ISSUE TITLE
Attempting to get a parent of a dir results in the same object

### ISSUE THREAD

**Issue by jaraco** [jaraco/zipp#7]
In ae4be5a, I illustrate an issue I discovered where retrieving the parent of a directory results in the same object and not actually the parent.

**Comment by asottile** [comment]
fwiw, cpython appears to have the same issue:

```pycon
$ python3.8
Python 3.8.0b2 (default, Jul  4 2019, 22:57:47) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipfile
>>> zip_path = zipfile.Path('t.zip')
>>> zip_path.joinpath('t').parent.at
''
```

**Comment by jaraco** [comment]
Reported upstream as [bpo-37520](https://bugs.python.org/issue37520).
